version: "3.8"

volumes:
  db_storage:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=sqlite
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - db_storage:/home/sqlite/n8n.db
